trigger:
- master
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build_Stage
  displayName: 
  jobs:
  - job: BuildNuget
    displayName: Build Nuget packages
    variables:
      BuildConfiguration: release
      MyRunNumber: $(GitVersion.SemVer).$(Rev:r)
      name: '1.0.0.$(Rev:r)'

    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/MyLib.Nuget.Corporate.csproj'
        feedsToUse: 'select'

    - task: UseGitVersion@5
      inputs:
        versionSpec: '5.*'
        includePrerelease: true

    - task: Assembly-Info-NetCore@2
      inputs:
        Path: '$(Build.SourcesDirectory)'
        FileNames: '**/MyLib.Nuget.Corporate.csproj'
        InsertAttributes: true
        FileEncoding: 'auto'
        WriteBOM: false
        VersionNumber: '$(Build.BuildNumber)'
        FileVersionNumber: '$(Build.BuildNumber)'
        PackageVersion: '$(Build.BuildNumber)'
        LogLevel: 'verbose'
        FailOnWarning: false
        DisableTelemetry: false
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/MyLib.Nuget.Corporate.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'pack'
        packagesToPack: '**/MyLib.Nuget.Corporate.csproj'
        versioningScheme: 'off'

    - task: PublishBuildArtifacts@1
      displayName: "Upload Artifacts"
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'ruggeri'